# Generated by Django 5.0.4 on 2024-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
