# Generated by Django 5.0.4 on 2024-04-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sale_sale_alter_sale_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale',
            new_name='sales',
        ),
    ]
