# Generated by Django 5.0.4 on 2024-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_sale_sale_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
