# Generated by Django 5.0.4 on 2024-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sale_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
