# Generated by Django 5.0.4 on 2024-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bill_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
